#!/bin/sh
set -ex
icons="
  arrow-back-outline
  arrow-down-outline
  arrow-forward-outline
  calendar-outline
  chatbubbles-outline
  checkmark-outline
  close-outline
  document-text-outline
  folder-open-outline
  logo-twitter
  logo-github
  logo-mastodon
  logo-rss
  person-outline
  pricetags-outline
  refresh-outline
  repeat-outline
  share-social-outline
  star-outline
  time-outline copy-outline
"
dest=ionicons
url=https://unpkg.com/ionicons@5.5.2/dist/svg/
mkdir -p "${dest}"
for icon in $icons; do
  icon="${icon}.svg"
  wget -O "${dest}/${icon}" "${url}/${icon}"
done